### ISSUE TITLE
threadpool.all.emit() & threadpool.any.emit() only support one 'eventData'

### ISSUE THREAD

**Issue by dionysusxie** [xk/node-threads-a-gogo#30]
threadpool.all.emit() & threadpool.any.emit() only support one 'eventData', please see the codes below:

function emitAll (event, data) {
    pool.forEach(function (v,i,o) {
      v.emit(event, data);
    });

```
return poolObject;
```

  }

But in the README, you wrote:
.all.emit( eventType, eventData [, eventData ... ] )

---

By the way, thank you for creating the 'threads-a-gogo' !
It's useful to me.

**Comment by xk** [comment]
fixed in 0.1.8
