### ISSUE TITLE
Cannot find module 'threads_a_gogo' in linux server

### ISSUE THREAD

**Issue by guypaskar** [xk/node-threads-a-gogo#43]
I have tested locally on my mac osx and it worked fine. (installed 0.1.7)

I tried to installing via npm on a dedicated (linux) server and this is what I get:

npm http GET https://registry.npmjs.org/threads_a_gogo
npm http 304 https://registry.npmjs.org/threads_a_gogo
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> threads_a_gogo@0.1.7 install /usr/local/lib/node_modules/threads_a_gogo
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/threads_a_gogo/build'
  CXX(target) Release/obj.target/threads_a_gogo/src/threads_a_gogo.o
  CC(target) Release/obj.target/threads_a_gogo/src/createPool.js.o
../src/createPool.js.c:1: warning: ‘kCreatePool_js’ defined but not used
  CC(target) Release/obj.target/threads_a_gogo/src/events.js.o
../src/events.js.c:1: warning: ‘kEvents_js’ defined but not used
  CC(target) Release/obj.target/threads_a_gogo/src/load.js.o
../src/load.js.c:1: warning: ‘kLoad_js’ defined but not used
  CC(target) Release/obj.target/threads_a_gogo/src/thread_nextTick.js.o
../src/thread_nextTick.js.c:1: warning: ‘kThread_nextTick_js’ defined but not used
  SOLINK_MODULE(target) Release/obj.target/threads_a_gogo.node
  SOLINK_MODULE(target) Release/obj.target/threads_a_gogo.node: Finished
  COPY Release/threads_a_gogo.node
make: Leaving directory `/usr/local/lib/node_modules/threads_a_gogo/build'
threads_a_gogo@0.1.7 /usr/local/lib/node_modules/threads_a_gogo
└── bindings@1.2.0

and then when I try to node tester.js (which just include the lib) I get:
Error: Cannot find module 'threads_a_gogo'

What am I missing here? it also seemed to install a different version (higher than 0.1.7 if I don't specify the specific version)

Thanks,
Guy

**Comment by xk** [comment]
Fixed. Thank you!
