### ISSUE TITLE
Error: Cannot find module 'threads_a_gogo'

### ISSUE THREAD

**Issue by filipvh** [xk/node-threads-a-gogo#47]
I've read a similar problem from a time ago, but compiling from git doesn't seem to sove the problem. Node version is v0.10.29, was v0.10.26 10 minutes ago and gave the same problems. Will include as much info as possible

I can get the module running on Mac OS X, but on my Linux server it simply won't work.
I've installed node-gyp globally, tried a bunch of stuff, but still get:

module.js:340
    throw err;
          ^
Error: Cannot find module 'threads_a_gogo'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Server.<anonymous> (/home/filip/new-node-t/server.js:6:18)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)

Tree in node_modules

.
└── threads_a_gogo
    ├── AUTHORS
    ├── LICENSE
    ├── README.md
    ├── benchmark
    │   ├── b00_fibonacci_server_no_threads.js
    │   ├── b01_fibonacci_server_threads.js
    │   ├── b02_fibonacci_server_threads_pool.js
    │   ├── b03_fibonacci_server_clustered.js
    │   ├── b04_only_quick.js
    │   ├── doubles.c
    │   ├── pi.c
    │   ├── pi.js
    │   ├── pi.rb
    │   └── pi_precompiled.js
    ├── binding.gyp
    ├── build
    │   ├── Makefile
    │   ├── Release
    │   │   ├── linker.lock
    │   │   ├── obj.target
    │   │   │   ├── threads_a_gogo
    │   │   │   │   └── src
    │   │   │   │       ├── createPool.js.o
    │   │   │   │       ├── events.js.o
    │   │   │   │       ├── load.js.o
    │   │   │   │       ├── thread_nextTick.js.o
    │   │   │   │       └── threads_a_gogo.o
    │   │   │   └── threads_a_gogo.node
    │   │   └── threads_a_gogo.node
    │   ├── binding.Makefile
    │   ├── config.gypi
    │   └── threads_a_gogo.target.mk
    ├── deps
    │   └── minifier
    │       ├── bin
    │       │   └── minify.osx
    │       └── src
    │           ├── minify.c
    │           ├── test
    │           ├── test.include.c
    │           └── test_minifier.c
    ├── examples
    │   ├── demo.js
    │   ├── ex01_basic.js
    │   ├── ex01_basic.md
    │   ├── ex02_events.js
    │   ├── ex02_events.md
    │   ├── ex03_ping_pong.js
    │   ├── ex03_ping_pong.md
    │   ├── ex04_main.js
    │   ├── ex04_main.md
    │   ├── ex04_worker.js
    │   ├── ex04_worker.md
    │   ├── ex05_pool.js
    │   ├── ex05_pool.md
    │   ├── ex06_complex.js
    │   ├── ex06_jason.js
    │   ├── ex06_jason.md
    │   ├── quickIntro_blocking.js
    │   ├── quickIntro_evented_childThreadCode.js
    │   ├── quickIntro_fiveThreads.js
    │   ├── quickIntro_loop.js
    │   ├── quickIntro_multiThread.js
    │   ├── quickIntro_multiThreadEvented.js
    │   ├── quickIntro_oneThread.js
    │   └── quickIntro_oneThreadEvented.js
    ├── lib
    │   └── index.js
    ├── node_modules
    │   └── bindings
    │       ├── README.md
    │       ├── bindings.js
    │       └── package.json
    ├── package.json
    ├── src
    │   ├── createPool.js
    │   ├── createPool.js.c
    │   ├── events.js
    │   ├── events.js.c
    │   ├── load.js
    │   ├── load.js.c
    │   ├── queues_a_gogo.cc
    │   ├── thread_nextTick.js
    │   ├── thread_nextTick.js.c
    │   └── threads_a_gogo.cc
    ├── test
    │   ├── ab.js
    │   ├── test00_run_once_and_destroy.js
    │   ├── test01_loop_as_fast_as_possible.js
    │   ├── test02_loop_as_fast_as_possible.js
    │   ├── test03_infiniteLoopFunction.js
    │   ├── test04_gc_versus_not_gc.js
    │   ├── test05_debugLeaksNoCallbacks.js
    │   ├── test06_throw_from_the_thread.js
    │   ├── test07_sigkill.js
    │   ├── test08_sigkill_leaks.js
    │   ├── test09_throw_from_the_callback.js
    │   ├── test10_node_nextTick_speed.js
    │   ├── test11_multi_callbacks.js
    │   ├── test12_precompiled_vs_normal.js
    │   ├── test13_thread_nextTick_speed.js
    │   ├── test14_emit_once.js
    │   ├── test15_emit_ping_pong.js
    │   ├── test16_syntax_error_in_the_thread.js
    │   ├── test17_pool_pi.js
    │   ├── test18_pool_any_as_fast_as_possible.js
    │   ├── test19_pool_emit_any_all.js
    │   ├── test20_removeAllListeners.js
    │   ├── test21_emit_ping_pong_big_string.js
    │   ├── test22_create_destroy_loop.js
    │   ├── test23_create_destroy_loop.js
    │   ├── test24_puts.js
    │   ├── test25_delete_puts.js
    │   ├── test26_puts_with_many_args.js
    │   ├── test27_puts_event_loop.js
    │   ├── test28_puts_nextTick_loop.js
    │   └── test29_puts_callback_loop.js
    └── wscript

**Comment by xk** [comment]
Fixed in c7970dd7e7c4a3638cf8ccabde7471f39b339e55
