### ISSUE TITLE
Is this repo still actively maintained?

### ISSUE THREAD

**Issue by jonjamz** [xk/node-threads-a-gogo#51]
I see some non-trivial PRs and unclosed issues going back a while.

I'm thinking about using this package in a project for work. Wondering how safe of a choice that would be. 

Would be grateful if someone could advise!

**Comment by jnfeinstein** [comment]
I don't think that it is being maintained.  I think there's another project that is API compatible using processes.  You could use that and then switch back to this project when it is maintained again.

**Comment by shaunc** [comment]
... um... @jnfeinstein what other project? :)

**Comment by jnfeinstein** [comment]
Well...it's a good idea amiright?

**Comment by dasantonym** [comment]
i guess that would be https://github.com/audreyt/node-webworker-threads

webworkers are included in io.js so i'd say it's safe to use them for threads.
