### ISSUE TITLE
Passing objects through emit functions

### ISSUE THREAD

**Issue by sean-hill** [xk/node-threads-a-gogo#52]
Hey is it possible to pass objects to a child thread? For instance.

```
var thread = require('threads_a_gogo').create();
thread.load(path.resolve(__dirname, './file.js'));

thread.emit('doSomething', { i: 'am', so: 'cool' });
```

When I currently do this, it's passing it as a string.

Thanks

**Comment by jnfeinstein** [comment]
Most JavaScript IPC is done using strings, so that doesn't surprise me.  Is the JSON parser available on the thread?  I can't recall.

**Comment by bjouhier** [comment]
V8 does not let us pass objects across isolates. You have to pass strings.

[JSON.parse is standardized by EcmaScript 5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.12) so it is supported by all modern JavaScript engines (including V8). You can use it to pass objects between threads.
