### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by amilajack** [xk/node-threads-a-gogo#57]
@xk I am willing to offer long term and active support for this project if that is fine with you.

I'm considering:
- Refactoring
- Offering test coverage
- Providing support for modern node versions
- Improving performance

**Comment by aisakeniudun** [comment]
great!that will be fine!

**Comment by amilajack** [comment]
@aisakeniudun Are you a contributor? I need confirmation from a contributor with read/write permission before I commit.
