### ISSUE TITLE
Licensing ?

### ISSUE THREAD

**Issue by netgusto** [xk/node-threads-a-gogo#63]
I'd like to contribute with MIT licensed code (restoring compatibility with newer node API, currently broken), but the closed license of thread_a_gogo forbids this. How can we proceed then ?

**Comment by netgusto** [comment]
The package.json explicitely states MIT license, unlike the LICENSE file. I guess it's MIT then ?

**Comment by xk** [comment]
Where does the package.json say that?

https://github.com/xk/node-threads-a-gogo/blob/master/package.json

**Comment by netgusto** [comment]
Can't find it. My mistake.

**Comment by xk** [comment]
Perhaps you've seen it @npmjs, that page erroneously says the license is MIT :-)

**Comment by xk** [comment]
Anyways, netgusto, use it as you like if you find it useful, I'm not going to sue you never ever wahahaha, really!

**Comment by xk** [comment]
"I hereby license my TAGG code to netgusto forever for 0$ royalties, signed Jorge Chamorro"

**Comment by xk** [comment]
Have a nice day!

**Comment by netgusto** [comment]
Thanks ! All the same to you !
